# Generated by Django 3.2.7 on 2021-11-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefas',
            name='data_criacao',
        ),
    ]
